-- ============================================================================
-- Fixed Expenses Setup Script
-- ============================================================================
-- Run this script once in Supabase SQL Editor before using the Import Template feature.
-- This creates the table structure, unique index, and RLS policies.
--
-- Instructions:
-- 1. Open Supabase Dashboard → SQL Editor
-- 2. Copy and paste this entire file
-- 3. Click "Run" (or Cmd/Ctrl + Enter)
-- ============================================================================

-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.fixed_expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon text DEFAULT '',
  name text NOT NULL,
  amount numeric NOT NULL,
  note text DEFAULT '',
  currency text DEFAULT 'CAD',
  sort_order int DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Unique index for onConflict:'name' (required for Import Template upsert)
CREATE UNIQUE INDEX IF NOT EXISTS fixed_expenses_name_key
  ON public.fixed_expenses (name);

-- Enable Row Level Security
ALTER TABLE public.fixed_expenses ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for clean re-runs)
DROP POLICY IF EXISTS "fe_select_all" ON public.fixed_expenses;
DROP POLICY IF EXISTS "fe_insert_auth" ON public.fixed_expenses;
DROP POLICY IF EXISTS "fe_update_auth" ON public.fixed_expenses;
DROP POLICY IF EXISTS "fe_delete_auth" ON public.fixed_expenses;

-- RLS Policy: Anyone can read fixed expenses
CREATE POLICY "fe_select_all"
  ON public.fixed_expenses FOR SELECT
  USING (true);

-- RLS Policy: Authenticated users can insert
CREATE POLICY "fe_insert_auth"
  ON public.fixed_expenses FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- RLS Policy: Authenticated users can update
CREATE POLICY "fe_update_auth"
  ON public.fixed_expenses FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- RLS Policy: Authenticated users can delete
CREATE POLICY "fe_delete_auth"
  ON public.fixed_expenses FOR DELETE
  USING (auth.role() = 'authenticated');

-- Updated_at trigger function
CREATE OR REPLACE FUNCTION public.update_fixed_expenses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists
DROP TRIGGER IF EXISTS trigger_fixed_expenses_updated_at ON public.fixed_expenses;

-- Create trigger
CREATE TRIGGER trigger_fixed_expenses_updated_at
  BEFORE UPDATE ON public.fixed_expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.update_fixed_expenses_updated_at();

-- Verify setup
DO $$
BEGIN
  RAISE NOTICE '✓ Fixed Expenses Setup Complete!';
  RAISE NOTICE '  - Table: public.fixed_expenses';
  RAISE NOTICE '  - Unique Index: fixed_expenses_name_key';
  RAISE NOTICE '  - RLS: Enabled with 4 policies';
  RAISE NOTICE '  - Trigger: update_fixed_expenses_updated_at';
  RAISE NOTICE '';
  RAISE NOTICE 'You can now use the Import Template feature in /fixed-expenses';
END $$;

-- Quick verification query
SELECT
  'fixed_expenses' as table_name,
  (SELECT COUNT(*) FROM public.fixed_expenses) as row_count,
  (SELECT COUNT(*) FROM pg_indexes WHERE tablename = 'fixed_expenses' AND indexname = 'fixed_expenses_name_key') as unique_index_exists,
  (SELECT COUNT(*) FROM pg_policies WHERE tablename = 'fixed_expenses') as policy_count;
