-- Create travel_expenses table for independent trip ledger records
-- This table is intentionally separate from accounts and transactions.
CREATE TABLE IF NOT EXISTS public.travel_expenses (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trip_key text NOT NULL DEFAULT 'mexico-2026-summer',
  trip_name text NOT NULL DEFAULT '2026 墨西哥暑假旅行',
  date date NOT NULL,
  record_type text NOT NULL,
  category text NOT NULL,
  description text DEFAULT '',
  original_amount numeric,
  original_currency text DEFAULT 'CAD',
  charged_amount numeric,
  charged_currency text DEFAULT 'CAD',
  cad_amount numeric NOT NULL DEFAULT 0,
  payment_method text DEFAULT '',
  funding_source text DEFAULT '',
  status text DEFAULT '估算中',
  note text DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.travel_expenses ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access their own travel ledger records
CREATE POLICY "Users can view their own travel expenses"
  ON public.travel_expenses
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own travel expenses"
  ON public.travel_expenses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own travel expenses"
  ON public.travel_expenses
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own travel expenses"
  ON public.travel_expenses
  FOR DELETE
  USING (auth.uid() = user_id);

-- Indexes for common travel ledger queries
CREATE INDEX IF NOT EXISTS idx_travel_expenses_user_id
  ON public.travel_expenses(user_id);

CREATE INDEX IF NOT EXISTS idx_travel_expenses_user_trip
  ON public.travel_expenses(user_id, trip_key);

CREATE INDEX IF NOT EXISTS idx_travel_expenses_user_trip_date
  ON public.travel_expenses(user_id, trip_key, date DESC);

CREATE INDEX IF NOT EXISTS idx_travel_expenses_user_trip_record_type
  ON public.travel_expenses(user_id, trip_key, record_type);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.update_travel_expenses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_travel_expenses_updated_at ON public.travel_expenses;

CREATE TRIGGER trigger_travel_expenses_updated_at
  BEFORE UPDATE ON public.travel_expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.update_travel_expenses_updated_at();

COMMENT ON TABLE public.travel_expenses IS 'Independent travel ledger records for trip-specific expense tracking';
