-- Create fixed_expenses table for user-configurable monthly fixed expenses
CREATE TABLE IF NOT EXISTS public.fixed_expenses (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  amount numeric NOT NULL,
  note text DEFAULT '',
  icon text DEFAULT '',
  currency text DEFAULT 'CAD',
  sort_order int DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.fixed_expenses ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access their own fixed expenses
CREATE POLICY "Users can view their own fixed expenses"
  ON public.fixed_expenses
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own fixed expenses"
  ON public.fixed_expenses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own fixed expenses"
  ON public.fixed_expenses
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own fixed expenses"
  ON public.fixed_expenses
  FOR DELETE
  USING (auth.uid() = user_id);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_fixed_expenses_user_id ON public.fixed_expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_fixed_expenses_active ON public.fixed_expenses(user_id, is_active);

-- Unique index on (user_id, name) for upsert operations (template import)
CREATE UNIQUE INDEX IF NOT EXISTS idx_fixed_expenses_user_name ON public.fixed_expenses(user_id, name);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.update_fixed_expenses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_fixed_expenses_updated_at
  BEFORE UPDATE ON public.fixed_expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.update_fixed_expenses_updated_at();

-- Seed data for existing users
-- Note: This will insert seed data for ALL existing users in auth.users
-- If you want to seed for a specific user, replace the INSERT..SELECT with individual INSERTs

INSERT INTO public.fixed_expenses (user_id, icon, name, amount, note, sort_order, is_active)
SELECT
  u.id,
  unnest(ARRAY['🏠', '🚗', '🏡', '🚘', '📅', '💡', '🔥', '🌐', '📱']) as icon,
  unnest(ARRAY['房贷', '汽车保险', '房屋保险', '车 lease', '地税', '水电', '煤气', '宽带', '电话费']) as name,
  unnest(ARRAY[4482.28, 497.13, 208.02, 817.22, 1560, 130, 130, 74, 169.47]) as amount,
  unnest(ARRAY['（每月28号）', '（每月23号）', '（每月23号）', '（每月10号）', '（4月1次，6月25号）', '（每月20号）≈', '（每月20号）≈', '（每月5号，信用卡A）', '（每月25号，信用卡B）']) as note,
  unnest(ARRAY[10, 20, 30, 40, 50, 60, 70, 80, 90]) as sort_order,
  true as is_active
FROM auth.users u
WHERE NOT EXISTS (
  SELECT 1 FROM public.fixed_expenses fe WHERE fe.user_id = u.id
);

COMMENT ON TABLE public.fixed_expenses IS 'User-configurable monthly fixed expenses';
